name: fingenai
description: AI-assisted financial tracker using Flutter, Firebase, and Provider.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.2

    # Firebase core + authentication + database
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.1.0

  # Sign-in provider (optional but useful)
  google_sign_in: ^6.2.1

  # Charts for finance visualization
  fl_chart: ^0.68.0

  # Utilities
  http: ^1.2.2
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  uuid: ^4.5.1

  # UI icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  # Example fonts (optional). Uncomment if you add custom fonts.
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
